"""Report assembly and export helpers.

``build_report`` wraps raw model output with a title and timestamp header.
``save_report`` writes a report to the ``outputs/`` folder with a safe filename.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

# outputs/ lives at the project root, one level above this package.
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "outputs"


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def slugify(name: str) -> str:
    """Turn an arbitrary system name into a filesystem-safe slug."""
    name = (name or "").strip().lower()
    name = re.sub(r"[^a-z0-9]+", "-", name).strip("-")
    return name or "threat-model"


def build_report(markdown_body: str, system_name: str | None = None) -> str:
    """Prepend a titled, timestamped header to the model's Markdown output."""
    title = (system_name or "").strip() or "Threat Model"
    timestamp = _utc_now().strftime("%Y-%m-%d %H:%M UTC")
    header = (
        f"# Threat Model — {title}\n\n"
        f"_Generated by the AI Threat Modeling Assistant on {timestamp}._\n\n"
        "---\n\n"
    )
    return header + (markdown_body or "").strip() + "\n"


def report_filename(system_name: str | None = None) -> str:
    """Build a unique, descriptive ``.md`` filename for a report."""
    stamp = _utc_now().strftime("%Y%m%d-%H%M%S")
    return f"{slugify(system_name or 'threat-model')}-{stamp}.md"


def save_report(
    markdown: str,
    system_name: str | None = None,
    output_dir: Path | str = OUTPUT_DIR,
) -> Path:
    """Write ``markdown`` to ``output_dir`` and return the file path."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / report_filename(system_name)
    path.write_text(markdown, encoding="utf-8")
    return path
